import { StoreProvider } from '@camino/store';
import { Inter } from 'next/font/google';
import './global.css';
import { ThemeProvider, Layout } from '@camino/ui';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter',
});

export const metadata = {
  title: 'Welcome to camino-suite',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col items-center justify-center w-full ${inter.variable}`}
      >
        <ThemeProvider>
          <StoreProvider>
            <Layout>{children}</Layout>
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
