import './global.css';

import { I18nProvider, Layout, ThemeProvider } from '@camino/ui';

import { Inter } from 'next/font/google';
import { StoreProvider } from '@camino/store';
import enTranslations from '../locales/en.json';
import esTranslations from '../locales/es.json';
import frTranslations from '../locales/fr.json';
import { AuthProvider } from '../context/AuthContext';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter'
});

const resources = {
  en: { translation: enTranslations },
  es: { translation: esTranslations },
  fr: { translation: frTranslations }
};

export const metadata = {
  title: 'Welcome to camino-suite',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col items-center justify-center w-full ${inter.variable}`}
      >
        <ThemeProvider>
          <StoreProvider>
            <AuthProvider>
              <I18nProvider resources={resources}>
                <Layout>{children}</Layout>
              </I18nProvider>
            </AuthProvider>
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
